
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CardsREST.Model
{

using System;
    using System.Collections.Generic;
    
public partial class AccountsType
{

    public AccountsType()
    {

        this.Accounts = new HashSet<Account>();

    }


    public int accountType { get; set; }

    public string nname { get; set; }

    public Nullable<int> aactive { get; set; }



    public virtual ICollection<Account> Accounts { get; set; }

}

}
