//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardsREST.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CardsEntities : DbContext
    {
        public CardsEntities()
            : base("name=CardsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AccountsType> AccountsTypes { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
    
        public virtual int PLZ_ADD_CLIENTE(string nUMDOC, string nAMECLIENT, string pHONECLIENT, string aDDRESSCLIENT, ObjectParameter rESPONSE)
        {
            var nUMDOCParameter = nUMDOC != null ?
                new ObjectParameter("NUMDOC", nUMDOC) :
                new ObjectParameter("NUMDOC", typeof(string));
    
            var nAMECLIENTParameter = nAMECLIENT != null ?
                new ObjectParameter("NAMECLIENT", nAMECLIENT) :
                new ObjectParameter("NAMECLIENT", typeof(string));
    
            var pHONECLIENTParameter = pHONECLIENT != null ?
                new ObjectParameter("PHONECLIENT", pHONECLIENT) :
                new ObjectParameter("PHONECLIENT", typeof(string));
    
            var aDDRESSCLIENTParameter = aDDRESSCLIENT != null ?
                new ObjectParameter("ADDRESSCLIENT", aDDRESSCLIENT) :
                new ObjectParameter("ADDRESSCLIENT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PLZ_ADD_CLIENTE", nUMDOCParameter, nAMECLIENTParameter, pHONECLIENTParameter, aDDRESSCLIENTParameter, rESPONSE);
        }
    
        public virtual int PLZ_TRANSACCION_PUNTOS(string nUMDOC, Nullable<int> pUNTOS, Nullable<int> tRANSCODE, Nullable<decimal> fACTORACRED, Nullable<decimal> fACTORCANJE, ObjectParameter rESPONSE)
        {
            var nUMDOCParameter = nUMDOC != null ?
                new ObjectParameter("NUMDOC", nUMDOC) :
                new ObjectParameter("NUMDOC", typeof(string));
    
            var pUNTOSParameter = pUNTOS.HasValue ?
                new ObjectParameter("PUNTOS", pUNTOS) :
                new ObjectParameter("PUNTOS", typeof(int));
    
            var tRANSCODEParameter = tRANSCODE.HasValue ?
                new ObjectParameter("TRANSCODE", tRANSCODE) :
                new ObjectParameter("TRANSCODE", typeof(int));
    
            var fACTORACREDParameter = fACTORACRED.HasValue ?
                new ObjectParameter("FACTORACRED", fACTORACRED) :
                new ObjectParameter("FACTORACRED", typeof(decimal));
    
            var fACTORCANJEParameter = fACTORCANJE.HasValue ?
                new ObjectParameter("FACTORCANJE", fACTORCANJE) :
                new ObjectParameter("FACTORCANJE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PLZ_TRANSACCION_PUNTOS", nUMDOCParameter, pUNTOSParameter, tRANSCODEParameter, fACTORACREDParameter, fACTORCANJEParameter, rESPONSE);
        }
    
        public virtual int PLZ_UPD_CARD_STATUS(string nUMDOC, Nullable<int> nUEVOESTATUS, ObjectParameter rESPONSE)
        {
            var nUMDOCParameter = nUMDOC != null ?
                new ObjectParameter("NUMDOC", nUMDOC) :
                new ObjectParameter("NUMDOC", typeof(string));
    
            var nUEVOESTATUSParameter = nUEVOESTATUS.HasValue ?
                new ObjectParameter("NUEVOESTATUS", nUEVOESTATUS) :
                new ObjectParameter("NUEVOESTATUS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PLZ_UPD_CARD_STATUS", nUMDOCParameter, nUEVOESTATUSParameter, rESPONSE);
        }
    
        public virtual int PLZ_ADD_CARD(string nUMDOC, ObjectParameter rESPONSE)
        {
            var nUMDOCParameter = nUMDOC != null ?
                new ObjectParameter("NUMDOC", nUMDOC) :
                new ObjectParameter("NUMDOC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PLZ_ADD_CARD", nUMDOCParameter, rESPONSE);
        }
    
        public virtual int PLZ_ADD_BATCH(string nUMDOC, string mONTO, Nullable<int> tRANSCODE, Nullable<decimal> fACTORACRED, Nullable<decimal> fACTORCANJE, string sUMAUSUARIO, ObjectParameter rESPONSE)
        {
            var nUMDOCParameter = nUMDOC != null ?
                new ObjectParameter("NUMDOC", nUMDOC) :
                new ObjectParameter("NUMDOC", typeof(string));
    
            var mONTOParameter = mONTO != null ?
                new ObjectParameter("MONTO", mONTO) :
                new ObjectParameter("MONTO", typeof(string));
    
            var tRANSCODEParameter = tRANSCODE.HasValue ?
                new ObjectParameter("TRANSCODE", tRANSCODE) :
                new ObjectParameter("TRANSCODE", typeof(int));
    
            var fACTORACREDParameter = fACTORACRED.HasValue ?
                new ObjectParameter("FACTORACRED", fACTORACRED) :
                new ObjectParameter("FACTORACRED", typeof(decimal));
    
            var fACTORCANJEParameter = fACTORCANJE.HasValue ?
                new ObjectParameter("FACTORCANJE", fACTORCANJE) :
                new ObjectParameter("FACTORCANJE", typeof(decimal));
    
            var sUMAUSUARIOParameter = sUMAUSUARIO != null ?
                new ObjectParameter("SUMAUSUARIO", sUMAUSUARIO) :
                new ObjectParameter("SUMAUSUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PLZ_ADD_BATCH", nUMDOCParameter, mONTOParameter, tRANSCODEParameter, fACTORACREDParameter, fACTORCANJEParameter, sUMAUSUARIOParameter, rESPONSE);
        }
    }
}
