//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardsREST.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransCode { get; set; }
        public string NName { get; set; }
        public string Description { get; set; }
        public Nullable<int> AActive { get; set; }
    }
}
